#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2013, Terradue S.r.l.                                            #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

if [ -z "${ONE_LOCATION}" ]; then
    JCLOUDS_LABSRC=/etc/one/im_jclouds-labs/im_jclouds-labsrc
    JCLOUDS_LABSCONF=/etc/one/im_jclouds-labs/im_jclouds-labs.conf
    MADCOMMON=/usr/lib/one/mads/madcommon.sh
    VAR_LOCATION=/var/lib/one 
else
    JCLOUDS_LABSRC=$ONE_LOCATION/etc/im_jclouds-labs/im_jclouds-labsrc
    JCLOUDS_LABSCONF=$ONE_LOCATION/etc/im_jclouds-labs/im_jclouds-labs.conf
    MADCOMMON=$ONE_LOCATION/lib/mads/madcommon.sh
    VAR_LOCATION=$ONE_LOCATION/var 
fi

. $MADCOMMON

# Export the vmm_mad specific rc
export_rc_vars $JCLOUDS_LABSRC

# Export provider capacity
export_rc_vars $JCLOUDS_LABSCONF

# Go to var directory ONE_LOCATION/var or /var/lib/one
cd $VAR_LOCATION

# Execute the actual MAD
execute_mad $*
